name: booking
description: "Booking Core mobile application."
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: 0.19.0
  flutter_native_splash: 2.4.5
  icons_launcher: 3.0.1
  firebase_core: 3.12.1
  shared_preferences: 2.5.2
  share_plus: 10.1.4
  dio: 5.8.0+1
  get_it: 8.0.3
  bloc: 9.0.0
  flutter_bloc: 9.1.0
  cached_network_image: 3.4.1
  google_maps_flutter: 2.10.1
  photo_view: 0.15.0
  video_player: 2.9.3
  webview_flutter: 4.10.0
  flutter_rating_bar: 4.0.1
  card_swiper: 3.0.1
  stream_transform: 2.1.1
  flutter_widget_from_html: 0.16.0
  timeago: 3.7.0
  flutter_svprogresshud: 1.1.0
  icofont_flutter: 1.4.0
  go_router: 14.8.1
  device_info_plus: 11.3.3
  flutter_secure_storage: 9.2.4
  shimmer: 3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 5.0.0

icons_launcher:
  image_path: "assets/images/ic_launcher.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  color_dark: "#ffffff"

  web: false

flutter:
  assets:
    - assets/images/
    - assets/localizations/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
        - asset: assets/fonts/OpenSans-BoldItalic.ttf
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
        - asset: assets/fonts/OpenSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/OpenSans-Italic.ttf
        - asset: assets/fonts/OpenSans-Light.ttf
        - asset: assets/fonts/OpenSans-LightItalic.ttf
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf
        - asset: assets/fonts/OpenSans-SemiBoldItalic.ttf
    - family: ProximaNova
      fonts:
        - asset: assets/fonts/ProximaNova-Black.otf
        - asset: assets/fonts/ProximaNova-Bold.otf
        - asset: assets/fonts/ProximaNova-Extrabld.otf
        - asset: assets/fonts/ProximaNova-Regular.otf
        - asset: assets/fonts/ProximaNovaT-Thin.otf
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Black.ttf
        - asset: assets/fonts/Raleway-BlackItalic.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
        - asset: assets/fonts/Raleway-BoldItalic.ttf
        - asset: assets/fonts/Raleway-ExtraBold.ttf
        - asset: assets/fonts/Raleway-ExtraBoldItalic.ttf
        - asset: assets/fonts/Raleway-ExtraLight.ttf
        - asset: assets/fonts/Raleway-ExtraLightItalic.ttf
        - asset: assets/fonts/Raleway-Italic.ttf
        - asset: assets/fonts/Raleway-Light.ttf
        - asset: assets/fonts/Raleway-LightItalic.ttf
        - asset: assets/fonts/Raleway-Medium.ttf
        - asset: assets/fonts/Raleway-MediumItalic.ttf
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-SemiBold.ttf
        - asset: assets/fonts/Raleway-SemiBoldItalic.ttf
        - asset: assets/fonts/Raleway-Thin.ttf
        - asset: assets/fonts/Raleway-ThinItalic.ttf

  uses-material-design: true
