name: booking
description: "Booking Core mobile application."
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.19.0

  flutter_native_splash: 2.4.2
  icons_launcher: 3.0.0
  firebase_core: 3.6.0
  shared_preferences: 2.3.2
  dio: 5.7.0
  realm: 20.0.0
  get_it: 8.0.0
  bloc: 8.1.4
  flutter_bloc: 8.1.6
  cached_network_image: 3.4.1
  flutter_svprogresshud:
    git:
      url: https://github.com/lucianokapluk/flutter_svprogresshud.git
      ref: master
  icofont_flutter: 1.4.0
  go_router: 14.3.0
  device_info_plus: 11.1.0
  flutter_secure_storage: 9.2.2
  shimmer: 3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 5.0.0

icons_launcher:
  image_path: "assets/images/ic_launcher.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  color_dark: "#ffffff"

  android_12:
    image: assets/images/logo.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/logo.png
    icon_background_color_dark: "#ffffff"

  web: false

flutter:
  assets:
    - assets/images/
    - assets/localizations/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
        - asset: assets/fonts/OpenSans-BoldItalic.ttf
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
        - asset: assets/fonts/OpenSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/OpenSans-Italic.ttf
        - asset: assets/fonts/OpenSans-Light.ttf
        - asset: assets/fonts/OpenSans-LightItalic.ttf
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf
        - asset: assets/fonts/OpenSans-SemiBoldItalic.ttf
    - family: ProximaNova
      fonts:
        - asset: assets/fonts/ProximaNova-Black.otf
        - asset: assets/fonts/ProximaNova-Bold.otf
        - asset: assets/fonts/ProximaNova-Extrabld.otf
        - asset: assets/fonts/ProximaNova-Regular.otf
        - asset: assets/fonts/ProximaNovaT-Thin.otf
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Black.ttf
        - asset: assets/fonts/Raleway-BlackItalic.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
        - asset: assets/fonts/Raleway-BoldItalic.ttf
        - asset: assets/fonts/Raleway-ExtraBold.ttf
        - asset: assets/fonts/Raleway-ExtraBoldItalic.ttf
        - asset: assets/fonts/Raleway-ExtraLight.ttf
        - asset: assets/fonts/Raleway-ExtraLightItalic.ttf
        - asset: assets/fonts/Raleway-Italic.ttf
        - asset: assets/fonts/Raleway-Light.ttf
        - asset: assets/fonts/Raleway-LightItalic.ttf
        - asset: assets/fonts/Raleway-Medium.ttf
        - asset: assets/fonts/Raleway-MediumItalic.ttf
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-SemiBold.ttf
        - asset: assets/fonts/Raleway-SemiBoldItalic.ttf
        - asset: assets/fonts/Raleway-Thin.ttf
        - asset: assets/fonts/Raleway-ThinItalic.ttf

  uses-material-design: true
