import 'package:flutter/material.dart';

extension IconFactory on Icons {
  static final Map<String, IconData> _iconMap = {
    'fa fa-building-o': Icons.night_shelter_outlined,
    'icofont-building-alt': Icons.apartment_outlined,
    'icofont-car': Icons.directions_car_filled_outlined,
    'icofont-island-alt': Icons.luggage,
    'icofont-ticket': Icons.local_activity_outlined,
    'icofont-ui-flight': Icons.flight_takeoff_outlined,
    'icofont-ship': Icons.directions_boat_outlined,
    'icofont-email': Icons.mark_email_unread_outlined,
    'apartments': Icons.apartment_outlined,
    'hotels': Icons.hotel_outlined,
    'homestays': Icons.home_outlined,
    'villas': Icons.villa_outlined,
    'boats': Icons.directions_boat_outlined,
    'motels': Icons.hotel_outlined,
    'resorts': Icons.hotel_outlined,
    'lodges': Icons.hotel_outlined,
    'holiday-homes': Icons.home_outlined,
    'cruises': Icons.directions_boat_outlined,
    'car-hire': Icons.directions_car_filled_outlined,
    'bicycle-hire': Icons.directions_bike_outlined,
    'flat-tv': Icons.desktop_windows_outlined,
    'laundry-and-dry-cleaning': Icons.restore_from_trash_outlined,
    'internet-wifi': Icons.wifi_outlined,
    'coffee-and-tea': Icons.free_breakfast_outlined,
    'havana-lobby-bar': Icons.local_bar_outlined,
    'tickets': Icons.local_activity_outlined,
    'fiesta-restaurant': Icons.restaurant_outlined,
    'hotel-transport-services': Icons.local_taxi_outlined,
    'laundry-services': Icons.restore_from_trash_outlined,
    'wake-up-call': Icons.alarm_on_outlined,
    'free-luggage-deposit': Icons.luggage_outlined,
    'pets-welcome': Icons.pets_outlined,
    'nature-adventure': Icons.nature_people_outlined,
    'activities': Icons.local_activity_outlined,
    'festival-events': Icons.event_outlined,
    'special-interest': Icons.star_outline,
    'wifi': Icons.wifi_outlined,
    'gymnasium': Icons.fitness_center_outlined,
    'mountain-bike': Icons.directions_bike_outlined,
    'satellite-office': Icons.work_outline,
    'staff-lounge': Icons.people_outlined,
    'golf-cages': Icons.sports_golf_outlined,
    'aerobics-room': Icons.sports_volleyball_outlined,
    'cultural': Icons.museum_outlined,
    'auditorium': Icons.meeting_room_outlined,
    'bar': Icons.local_bar_outlined,
    'cafe': Icons.local_cafe_outlined,
    'office': Icons.work_outline,
    'party-hall': Icons.party_mode_outlined,
    'recording-studio': Icons.mic_outlined,
    'yoga-studio': Icons.self_improvement_outlined,
    'villa': Icons.villa_outlined,
    'air-conditioning': Icons.ac_unit_outlined,
    'kitchen': Icons.kitchen_outlined,
    'parking': Icons.local_parking_outlined,
    'pool': Icons.pool_outlined,
    'breakfast': Icons.free_breakfast_outlined,
    'wi-fi-internet': Icons.wifi_outlined,
    'fm-radio': Icons.radio_outlined,
    'power-windows': Icons.window_outlined,
    'sensor-lock': Icons.lock_outlined,
    'speed-km': Icons.speed_outlined,
  };

  static IconData get(
    String? name, {
    IconData defaultIcon = Icons.error_outline,
  }) {
    return _iconMap[name] ?? defaultIcon;
  }
}
